dist: trusty

os: linux

language: php

notifications:
  email:
    recipients:
      - plugins@cleantalk.org
    on_failure: always
    on_success: never

jobs:
  include:
    - env: TRAVISCI=phpunit
    - env: TRAVISCI=phpcs

before_script:
  - |
    if [[ "$TRAVISCI" == "phpunit" ]] ; then
      composer require --dev phpunit/phpunit 7.*
    fi
  - |
    if [[ "$TRAVISCI" == "phpcs" ]] ; then
      composer require --dev squizlabs/php_codesniffer
      composer require --dev phpcompatibility/php-compatibility
      vendor/bin/phpcs --config-set installed_paths vendor/phpcompatibility/php-compatibility
    fi

script:
  - |
    if [[ "$TRAVISCI" == "phpunit" ]] ; then
      vendor/bin/phpunit --configuration tests/phpunit.xml
    fi
  - |
    if [[ "$TRAVISCI" == "phpcs" ]] ; then
      vendor/bin/phpcs --standard=tests/.phpcs.xml
    fi
