<?php

use Cleantalk\Common\RC;

class RCTest extends PHPUnit\Framework\TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $_GET['spbc_remote_call_token'] = 'token';
        $_GET['spbc_remote_call_action'] = 'sfw_update';
        $_GET['plugin_name'] = 'antispam';
    }

    public function testCheck() {
        $rc_check = RC::check();
        self::assertTrue( $rc_check );
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        unset( $_GET['spbc_remote_call_token'], $_GET['spbc_remote_call_action'], $_GET['plugin_name'] );
    }
}
